spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: chp-bmboagt01.corp.chpinfo.com:9092
                    zk-nodes: chp-bmboagt01.corp.chpinfo.com:2181
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

server:
    session:
        cookie:
            http-only: true

security:
    basic:
        enabled: false


eureka:
    instance:
        appname: ${spring.application.name}
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000 
    eureka:
        enabled: true
zuul:
    host:
        connect-timeout-millis: 30000
        socket-timeout-millis: 30000

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 30000

management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
        binders:
            enabled: true
            
            
logging:
    level:
        ROOT: INFO
        io.tronbot: DEBUG
        io.tronbot.dc.common.json: INFO
        
data-concierge: 
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 100000
    cache:
        hazelcast: 
            port: 5701
            backup-Count: 1
            write-batch-size: 10000
            write-delay: 60
            time-to-live-seconds: 12004800