server:
  port: ${PORT:9999}

spring:
    application:
        name: data-concierge-gateway

## Disable Hystrix timeout globally (for all services)
hystrix: 
  command: 
    default:
      execution:
        timeout:
          enabled: false
