message: Hello Spring One!!!!!!
server:
  port: ${PORT:8000}
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: data-concierge
          group: data-concierge-group
          durableSubscription: true
google:
  places:
    api:
      url: https://maps.googleapis.com/maps/api/place/
      api: AIzaSyCm-1Aopq9QMUd--8E0Rxuue-iHhjYTjqQ
      timeout: 2000